# SEO
title: Benjamin Oakes
description: >
  A programmer, sustainability enthusiast, and community builder in Iowa City.
author: Benjamin Oakes
github:
  username: benjaminoakes
linkedin:
  username: benjaminoakes
twitter:
  username: benjaminoakes

url: "http://staging.benjaminoakes.com"
baseurl: ""
permalink: pretty

adsense:
  ad_client: "ca-pub-5788066382467641"
  ad_slot: "2987007375"
  ad_format: "auto"

disqus:
  shortname: "benjaminoakes"

feedburner:
  feed_address: "BenjaminOakes"

google_analytics: "UA-26383944-1"

paginate: 10
paginate_path: "/page/:num"

markdown: kramdown
theme: minima # Maybe change to hydejack
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
exclude:
  - CNAME
  - docker-compose.yml
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - script
  - todo.md
  - qa.md
